In [1]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

In [2]:
X=pd.read_csv("X")

In [3]:
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [4]:
Y=pd.read_csv("Y")

In [5]:
Y.head()

   target
0       1
1       1
2       1
3       1
4       1

In [10]:
Y = Y.squeeze()
Y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [28]:
X = np.asarray(X)

### GridSearchCV

In [29]:
# loading the SVC model
model = SVC()

In [30]:
# hyperparameters

parameters = {
              'kernel':['linear','poly','rbf','sigmoid'],
              'C':[1, 5, 10, 20]
}

In [31]:
# grid search
classifier = GridSearchCV(model, parameters, cv=5)

In [32]:
# fitting the data to our model
classifier.fit(X, Y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 5, 10, 20],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [21]:
classifier.cv_results_

{'mean_fit_time': array([1.06635070e+00, 4.21385765e-03, 5.38430214e-03, 7.47661591e-03,
        3.88897567e+00, 4.44507599e-03, 5.35736084e-03, 5.92770576e-03,
        6.92433262e+00, 5.38372993e-03, 5.42244911e-03, 5.23376465e-03,
        9.35933151e+00, 7.06110001e-03, 5.21893501e-03, 4.87804413e-03]),
 'std_fit_time': array([6.18995858e-01, 3.89699829e-04, 4.87013322e-04, 4.62156650e-04,
        9.95172422e-01, 4.99202436e-04, 3.61539260e-04, 2.06643565e-04,
        1.83493632e+00, 5.65014508e-04, 4.73889553e-04, 3.81773262e-04,
        5.00954767e+00, 8.87683512e-04, 4.23710464e-04, 4.22543592e-04]),
 'mean_score_time': array([0.0015902 , 0.0012207 , 0.00162296, 0.00189714, 0.00106392,
        0.00141373, 0.00139809, 0.00198421, 0.00100513, 0.00129924,
        0.00141025, 0.00160213, 0.00143533, 0.0010006 , 0.00159683,
        0.00179706]),
 'std_score_time': array([5.02462784e-04, 3.89263817e-04, 4.56224461e-04, 4.88562428e-05,
        1.31920652e-04, 5.07142235e-04, 4.88034853e-04, 6.84719896e-05,
        1.38063915e-05, 4.02589594e-04, 4.70676875e-04, 5.06947478e-04,
        4.40290461e-04, 2.01403733e-06, 4.88538707e-04, 3.99162963e-04]),
 'param_C': masked_array(data=[1, 1, 1, 1, 5, 5, 5, 5, 10, 10, 10, 10, 20, 20, 20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'poly', 'rbf', 'sigmoid', 'linear', 'poly',
                    'rbf', 'sigmoid', 'linear', 'poly', 'rbf', 'sigmoid',
                    'linear', 'poly', 'rbf', 'sigmoid'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'poly'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'sigmoid'},
  {'C': 5, 'kernel': 'linear'},
  {'C': 5, 'kernel': 'poly'},
  {'C': 5, 'kernel': 'rbf'},
  {'C': 5, 'kernel': 'sigmoid'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'poly'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'sigmoid'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'poly'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'sigmoid'}],
 'split0_test_score': array([0.81967213, 0.67213115, 0.60655738, 0.54098361, 0.80327869,
        0.67213115, 0.67213115, 0.47540984, 0.7704918 , 0.68852459,
        0.67213115, 0.45901639, 0.7704918 , 0.73770492, 0.67213115,
        0.47540984]),
 'split1_test_score': array([0.8852459 , 0.60655738, 0.60655738, 0.54098361, 0.91803279,
        0.67213115, 0.6557377 , 0.45901639, 0.91803279, 0.67213115,
        0.68852459, 0.44262295, 0.90163934, 0.68852459, 0.70491803,
        0.45901639]),
 'split2_test_score': array([0.80327869, 0.68852459, 0.73770492, 0.52459016, 0.78688525,
        0.67213115, 0.72131148, 0.6557377 , 0.7704918 , 0.67213115,
        0.70491803, 0.6557377 , 0.83606557, 0.70491803, 0.67213115,
        0.63934426]),
 'split3_test_score': array([0.86666667, 0.7       , 0.68333333, 0.55      , 0.83333333,
        0.78333333, 0.71666667, 0.51666667, 0.86666667, 0.76666667,
        0.73333333, 0.5       , 0.8       , 0.75      , 0.75      ,
        0.48333333]),
 'split4_test_score': array([0.76666667, 0.6       , 0.58333333, 0.55      , 0.75      ,
        0.7       , 0.66666667, 0.48333333, 0.76666667, 0.7       ,
        0.7       , 0.48333333, 0.78333333, 0.68333333, 0.71666667,
        0.48333333]),
 'mean_test_score': array([0.82830601, 0.65344262, 0.64349727, 0.54131148, 0.81830601,
        0.69994536, 0.68650273, 0.51803279, 0.81846995, 0.69989071,
        0.69978142, 0.50814208, 0.81830601, 0.71289617, 0.7031694 ,
        0.50808743]),
 'std_test_score': array([0.04292787, 0.04195697, 0.05798414, 0.00928222, 0.05665694,
        0.04306843, 0.02708509, 0.07136976, 0.06248691, 0.03501261,
        0.02021592, 0.07638367, 0.04712588, 0.02654714, 0.02934309,
        0.0662264 ]),
 'rank_test_score': array([ 1, 11, 12, 13,  3,  7, 10, 14,  2,  8,  9, 15,  3,  5,  6, 16])}

In [22]:
# best parameters

best_parameters = classifier.best_params_
print(best_parameters)

{'C': 1, 'kernel': 'linear'}

In [23]:
# higest accuracy

highest_accuracy = classifier.best_score_
print(highest_accuracy)

0.8283060109289618

In [24]:
# loading the results to pandas dataframe
result = pd.DataFrame(classifier.cv_results_)

In [25]:
result.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,1.066351,0.618996,0.001590,0.000502,1,linear,"{'C': 1, 'kernel': 'linear'}",0.819672,0.885246,0.803279,0.866667,0.766667,0.828306,0.042928,1
1,0.004214,0.000390,0.001221,0.000389,1,poly,"{'C': 1, 'kernel': 'poly'}",0.672131,0.606557,0.688525,0.700000,0.600000,0.653443,0.041957,11
2,0.005384,0.000487,0.001623,0.000456,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.606557,0.606557,0.737705,0.683333,0.583333,0.643497,0.057984,12
3,0.007477,0.000462,0.001897,0.000049,1,sigmoid,"{'C': 1, 'kernel': 'sigmoid'}",0.540984,0.540984,0.524590,0.550000,0.550000,0.541311,0.009282,13
4,3.888976,0.995172,0.001064,0.000132,5,linear,"{'C': 5, 'kernel': 'linear'}",0.803279,0.918033,0.786885,0.833333,0.750000,0.818306,0.056657,3

In [26]:
grid_search_result = result[['param_C','param_kernel','mean_test_score']]

In [27]:
grid_search_result

   param_C param_kernel  mean_test_score
0        1       linear         0.828306
1        1         poly         0.653443
2        1          rbf         0.643497
3        1      sigmoid         0.541311
4        5       linear         0.818306
5        5         poly         0.699945
6        5          rbf         0.686503
7        5      sigmoid         0.518033
8       10       linear         0.818470
9       10         poly         0.699891
10      10          rbf         0.699781
11      10      sigmoid         0.508142
12      20       linear         0.818306
13      20         poly         0.712896
14      20          rbf         0.703169
15      20      sigmoid         0.508087

Highest Accuracy = 82.8%

Best Parameters = {'C':1, 'kernel':'linear'}

### RandomizedSearchCV

In [33]:
# loading the SVC model
model = SVC()

In [34]:
# hyperparameters

parameters = {
              'kernel':['linear','poly','rbf','sigmoid'],
              'C':[1, 5, 10, 20]
}

In [36]:
# grid search
from sklearn.model_selection import RandomizedSearchCV
classifier = RandomizedSearchCV(model, parameters, cv=5)

In [37]:
# fitting the data to our model
classifier.fit(X, Y)

RandomizedSearchCV(cv=5, estimator=SVC(),
                   param_distributions={'C': [1, 5, 10, 20],
                                        'kernel': ['linear', 'poly', 'rbf',
                                                   'sigmoid']})

In [38]:
classifier.cv_results_

{'mean_fit_time': array([1.16821766e-02, 5.12199402e-03, 5.57556152e-03, 1.05404534e+00,
        4.98614311e-03, 6.98142052e-03, 5.18784523e-03, 4.75664139e-03,
        6.91852851e+00, 5.33571243e-03]),
 'std_fit_time': array([3.42983743e-03, 2.38816473e-04, 4.89663857e-04, 5.54218990e-01,
        2.80727120e-06, 8.89671998e-04, 4.02168784e-04, 4.50617508e-04,
        1.68697831e+00, 4.33578791e-04]),
 'mean_score_time': array([0.00398798, 0.00160637, 0.00120001, 0.00099893, 0.00158801,
        0.00104632, 0.00159502, 0.00120049, 0.00119529, 0.00119567]),
 'std_score_time': array([1.78627467e-03, 4.81293563e-04, 3.97451434e-04, 1.26519195e-06,
        4.95897110e-04, 6.12637590e-05, 4.88038743e-04, 4.04461289e-04,
        3.99822501e-04, 4.00202214e-04]),
 'param_kernel': masked_array(data=['sigmoid', 'rbf', 'rbf', 'linear', 'sigmoid', 'poly',
                    'sigmoid', 'poly', 'linear', 'poly'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_array(data=[1, 5, 20, 1, 20, 20, 10, 5, 10, 10],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'params': [{'kernel': 'sigmoid', 'C': 1},
  {'kernel': 'rbf', 'C': 5},
  {'kernel': 'rbf', 'C': 20},
  {'kernel': 'linear', 'C': 1},
  {'kernel': 'sigmoid', 'C': 20},
  {'kernel': 'poly', 'C': 20},
  {'kernel': 'sigmoid', 'C': 10},
  {'kernel': 'poly', 'C': 5},
  {'kernel': 'linear', 'C': 10},
  {'kernel': 'poly', 'C': 10}],
 'split0_test_score': array([0.54098361, 0.67213115, 0.67213115, 0.81967213, 0.47540984,
        0.73770492, 0.45901639, 0.67213115, 0.7704918 , 0.68852459]),
 'split1_test_score': array([0.54098361, 0.6557377 , 0.70491803, 0.8852459 , 0.45901639,
        0.68852459, 0.44262295, 0.67213115, 0.91803279, 0.67213115]),
 'split2_test_score': array([0.52459016, 0.72131148, 0.67213115, 0.80327869, 0.63934426,
        0.70491803, 0.6557377 , 0.67213115, 0.7704918 , 0.67213115]),
 'split3_test_score': array([0.55      , 0.71666667, 0.75      , 0.86666667, 0.48333333,
        0.75      , 0.5       , 0.78333333, 0.86666667, 0.76666667]),
 'split4_test_score': array([0.55      , 0.66666667, 0.71666667, 0.76666667, 0.48333333,
        0.68333333, 0.48333333, 0.7       , 0.76666667, 0.7       ]),
 'mean_test_score': array([0.54131148, 0.68650273, 0.7031694 , 0.82830601, 0.50808743,
        0.71289617, 0.50814208, 0.69994536, 0.81846995, 0.69989071]),
 'std_test_score': array([0.00928222, 0.02708509, 0.02934309, 0.04292787, 0.0662264 ,
        0.02654714, 0.07638367, 0.04306843, 0.06248691, 0.03501261]),
 'rank_test_score': array([ 8,  7,  4,  1, 10,  3,  9,  5,  2,  6])}

In [39]:
# best parameters

best_parameters = classifier.best_params_
print(best_parameters)

{'kernel': 'linear', 'C': 1}

In [40]:
# higest accuracy

highest_accuracy = classifier.best_score_
print(highest_accuracy)

0.8283060109289618

In [41]:
# loading the results to pandas dataframe
result = pd.DataFrame(classifier.cv_results_)

In [42]:
result.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.011682,0.003430,0.003988,0.001786,sigmoid,1,"{'kernel': 'sigmoid', 'C': 1}",0.540984,0.540984,0.524590,0.550000,0.550000,0.541311,0.009282,8
1,0.005122,0.000239,0.001606,0.000481,rbf,5,"{'kernel': 'rbf', 'C': 5}",0.672131,0.655738,0.721311,0.716667,0.666667,0.686503,0.027085,7
2,0.005576,0.000490,0.001200,0.000397,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.672131,0.704918,0.672131,0.750000,0.716667,0.703169,0.029343,4
3,1.054045,0.554219,0.000999,0.000001,linear,1,"{'kernel': 'linear', 'C': 1}",0.819672,0.885246,0.803279,0.866667,0.766667,0.828306,0.042928,1
4,0.004986,0.000003,0.001588,0.000496,sigmoid,20,"{'kernel': 'sigmoid', 'C': 20}",0.475410,0.459016,0.639344,0.483333,0.483333,0.508087,0.066226,10

In [43]:
randomized_search_result = result[['param_C','param_kernel','mean_test_score']]

In [44]:
randomized_search_result

  param_C param_kernel  mean_test_score
0       1      sigmoid         0.541311
1       5          rbf         0.686503
2      20          rbf         0.703169
3       1       linear         0.828306
4      20      sigmoid         0.508087
5      20         poly         0.712896
6      10      sigmoid         0.508142
7       5         poly         0.699945
8      10       linear         0.818470
9      10         poly         0.699891

Highest Accuracy = 82.8%

Best Parameters = {'C':1, 'kernel':'linear'}